#
#Copyright (C) 2016 The Android Open-Source Project
#
#Licensed Under the Apache License, Version 2.0 (the "License");
#You may only use this file in compliance with the License
#
#
#This BoardConfig.mk was originally made by Qiangong2 for the D190U
#
#Do Not Edit any text above and including this line
#Feel free to edit anything below this line :)
#
#
# Thanks BLU for NOT providing the source code... -_-

#Assert
TARGET_OTA_ASSERT_DEVICE := D190U,d190u,scx15_sp7715ga_FS001

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := false
ARCH_ARM_HAVE_TLS_REGISTER := true

#Platform
TARGET_BOARD_PLATFORM := scx15
TARGET_BOOTLOADER_BOARD_NAME := scx15_sp7715ga

#config u-boot
TARGET_NO_KERNEL := false
TARGET_NO_BOOTLOADER := false

#Kernel
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_PREBUILT_KERNEL := device/blu/scx15_sp7715ga_FS001/zImage
BOARD_USES_UNCOMPRESSED_BOOT := true

#Userimages
BOARD_BOOTIMAGE_PARTITION_SIZE := 113141350
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 113141350
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 350000000
#BOARD_CACHEIMAGE_PARTITION_SIZE := 10000000
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ubifs
BOARD_FLASH_BLOCK_SIZE := 4096

#Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
TARGET_RECOVERY_FSTAB := device/blu/scx15_sp7715ga_FS001/nand/twrp.fstab
TARGET_USERIMAGES_USE_UBIFS := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_SUPPRESS_EMMC_WIPE := true

#TWRP
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_SCREEN_TIMEOUT := true
TWRP_INCLUDE_LOGCAT := true
DEVICE_RESOLUTION := 320x480
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
TW_CUSTOM_POWER_BUTTON := 116
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_FLASH_FROM_STORAGE := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_HAS_DOWNLOAD_MODE := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
